module Dedalus
  class CreateParams = Dedalus::Models::CreateParams

  class LifecycleStatus = Dedalus::Models::LifecycleStatus

  class Machine = Dedalus::Models::Machine

  class MachineCreateParams = Dedalus::Models::MachineCreateParams

  class MachineDeleteParams = Dedalus::Models::MachineDeleteParams

  class MachineList = Dedalus::Models::MachineList

  class MachineListItem = Dedalus::Models::MachineListItem

  class MachineListParams = Dedalus::Models::MachineListParams

  class MachineRetrieveParams = Dedalus::Models::MachineRetrieveParams

  module Machines = Dedalus::Models::Machines

  class MachineSleepParams = Dedalus::Models::MachineSleepParams

  class MachineUpdateParams = Dedalus::Models::MachineUpdateParams

  class MachineWakeParams = Dedalus::Models::MachineWakeParams

  class UpdateParams = Dedalus::Models::UpdateParams
end
