module Dedalus
  module Resources
    class Machines
      class Terminals
        def create: (
          machine_id: String,
          height: Integer,
          width: Integer,
          ?cwd: String,
          ?env: ::Hash[Symbol, String],
          ?shell: String,
          ?request_options: Dedalus::request_opts
        ) -> Dedalus::Machines::Terminal

        def retrieve: (
          machine_id: String,
          terminal_id: String,
          ?request_options: Dedalus::request_opts
        ) -> Dedalus::Machines::Terminal

        def list: (
          machine_id: String,
          ?cursor: String,
          ?limit: Integer,
          ?request_options: Dedalus::request_opts
        ) -> Dedalus::Internal::CursorPage[Dedalus::Machines::Terminal]

        def delete: (
          machine_id: String,
          terminal_id: String,
          ?request_options: Dedalus::request_opts
        ) -> Dedalus::Machines::Terminal

        def initialize: (client: Dedalus::Client) -> void
      end
    end
  end
end
