# frozen_string_literal: true

# Standard libraries.
# rubocop:disable Lint/RedundantRequireStatement
require "English"
require "base64"
require "cgi"
require "date"
require "erb"
require "etc"
require "json"
require "net/http"
require "openssl"
require "pathname"
require "rbconfig"
require "securerandom"
require "set"
require "stringio"
require "time"
require "uri"
# rubocop:enable Lint/RedundantRequireStatement

# We already ship the preferred sorbet manifests in the package itself.
# `tapioca` currently does not offer us a way to opt out of unnecessary compilation.
if Object.const_defined?(:Tapioca) &&
   caller.chain([$PROGRAM_NAME]).chain(ARGV).any?(/tapioca/) &&
   ARGV.none?(/dsl/)
  return
end

# Gems.
require "connection_pool"

# Package files.
require_relative "dedalus/version"
require_relative "dedalus/internal/util"
require_relative "dedalus/internal/type/converter"
require_relative "dedalus/internal/type/unknown"
require_relative "dedalus/internal/type/boolean"
require_relative "dedalus/internal/type/file_input"
require_relative "dedalus/internal/type/enum"
require_relative "dedalus/internal/type/union"
require_relative "dedalus/internal/type/array_of"
require_relative "dedalus/internal/type/hash_of"
require_relative "dedalus/internal/type/base_model"
require_relative "dedalus/internal/type/base_page"
require_relative "dedalus/internal/type/base_stream"
require_relative "dedalus/internal/type/request_parameters"
require_relative "dedalus/internal"
require_relative "dedalus/request_options"
require_relative "dedalus/file_part"
require_relative "dedalus/errors"
require_relative "dedalus/internal/transport/base_client"
require_relative "dedalus/internal/transport/pooled_net_requester"
require_relative "dedalus/client"
require_relative "dedalus/internal/stream"
require_relative "dedalus/internal/cursor_page"
require_relative "dedalus/models/create_params"
require_relative "dedalus/models/machines/ssh_session_create_params"
require_relative "dedalus/models/update_params"
require_relative "dedalus/models/lifecycle_status"
require_relative "dedalus/models/machine"
require_relative "dedalus/models/machine_compute_usage"
require_relative "dedalus/models/machine_compute_usage_row"
require_relative "dedalus/models/machine_create_params"
require_relative "dedalus/models/machine_delete_params"
require_relative "dedalus/models/machine_list"
require_relative "dedalus/models/machine_list_item"
require_relative "dedalus/models/machine_list_params"
require_relative "dedalus/models/machine_retrieve_params"
require_relative "dedalus/models/machines/artifact"
require_relative "dedalus/models/machines/artifact_delete_params"
require_relative "dedalus/models/machines/artifact_list"
require_relative "dedalus/models/machines/artifact_list_params"
require_relative "dedalus/models/machines/artifact_ref"
require_relative "dedalus/models/machines/artifact_retrieve_params"
require_relative "dedalus/models/machines/execution"
require_relative "dedalus/models/machines/execution_create_params"
require_relative "dedalus/models/machines/execution_delete_params"
require_relative "dedalus/models/machines/execution_event"
require_relative "dedalus/models/machines/execution_events"
require_relative "dedalus/models/machines/execution_events_params"
require_relative "dedalus/models/machines/execution_list"
require_relative "dedalus/models/machines/execution_list_params"
require_relative "dedalus/models/machines/execution_output"
require_relative "dedalus/models/machines/execution_output_params"
require_relative "dedalus/models/machines/execution_retrieve_params"
require_relative "dedalus/models/machines/preview"
require_relative "dedalus/models/machines/preview_create_params"
require_relative "dedalus/models/machines/preview_delete_params"
require_relative "dedalus/models/machines/preview_list"
require_relative "dedalus/models/machines/preview_list_params"
require_relative "dedalus/models/machines/preview_retrieve_params"
require_relative "dedalus/models/machines/ssh_connection"
require_relative "dedalus/models/machines/ssh_create_params"
require_relative "dedalus/models/machines/ssh_delete_params"
require_relative "dedalus/models/machines/ssh_host_trust"
require_relative "dedalus/models/machines/ssh_list_params"
require_relative "dedalus/models/machines/ssh_retrieve_params"
require_relative "dedalus/models/machines/ssh_session"
require_relative "dedalus/models/machines/ssh_session_list"
require_relative "dedalus/models/machines/terminal"
require_relative "dedalus/models/machines/terminal_client_event"
require_relative "dedalus/models/machines/terminal_closed_event"
require_relative "dedalus/models/machines/terminal_connect_params"
require_relative "dedalus/models/machines/terminal_create_params"
require_relative "dedalus/models/machines/terminal_delete_params"
require_relative "dedalus/models/machines/terminal_error_event"
require_relative "dedalus/models/machines/terminal_input_event"
require_relative "dedalus/models/machines/terminal_list"
require_relative "dedalus/models/machines/terminal_list_params"
require_relative "dedalus/models/machines/terminal_output_event"
require_relative "dedalus/models/machines/terminal_resize_event"
require_relative "dedalus/models/machines/terminal_retrieve_params"
require_relative "dedalus/models/machines/terminal_server_event"
require_relative "dedalus/models/machine_sleep_params"
require_relative "dedalus/models/machine_storage_usage"
require_relative "dedalus/models/machine_storage_usage_row"
require_relative "dedalus/models/machine_update_params"
require_relative "dedalus/models/machine_wake_params"
require_relative "dedalus/models/machine_watch_params"
require_relative "dedalus/models/org_usage"
require_relative "dedalus/models/usage_machine_compute_params"
require_relative "dedalus/models/usage_machine_storage_params"
require_relative "dedalus/models/usage_retrieve_params"
require_relative "dedalus/models"
require_relative "dedalus/resources/machines"
require_relative "dedalus/resources/machines/artifacts"
require_relative "dedalus/resources/machines/executions"
require_relative "dedalus/resources/machines/previews"
require_relative "dedalus/resources/machines/ssh"
require_relative "dedalus/resources/machines/terminals"
require_relative "dedalus/resources/usage"
