module Dedalus
  module Models
    module Machines
      type preview_create_params =
        {
          port: Integer,
          protocol: Dedalus::Models::Machines::PreviewCreateParams::protocol,
          visibility: Dedalus::Models::Machines::PreviewCreateParams::visibility
        }

      class PreviewCreateParams < Dedalus::Internal::Type::BaseModel
        attr_accessor port: Integer

        attr_reader protocol: Dedalus::Models::Machines::PreviewCreateParams::protocol?

        def protocol=: (
          Dedalus::Models::Machines::PreviewCreateParams::protocol
        ) -> Dedalus::Models::Machines::PreviewCreateParams::protocol

        attr_reader visibility: Dedalus::Models::Machines::PreviewCreateParams::visibility?

        def visibility=: (
          Dedalus::Models::Machines::PreviewCreateParams::visibility
        ) -> Dedalus::Models::Machines::PreviewCreateParams::visibility

        def initialize: (
          port: Integer,
          ?protocol: Dedalus::Models::Machines::PreviewCreateParams::protocol,
          ?visibility: Dedalus::Models::Machines::PreviewCreateParams::visibility
        ) -> void

        def to_hash: -> {
          port: Integer,
          protocol: Dedalus::Models::Machines::PreviewCreateParams::protocol,
          visibility: Dedalus::Models::Machines::PreviewCreateParams::visibility
        }

        type protocol = :http | :https

        module Protocol
          extend Dedalus::Internal::Type::Enum

          HTTP: :http
          HTTPS: :https

          def self?.values: -> ::Array[Dedalus::Models::Machines::PreviewCreateParams::protocol]
        end

        type visibility = :public | :private | :org

        module Visibility
          extend Dedalus::Internal::Type::Enum

          PUBLIC: :public
          PRIVATE: :private
          ORG: :org

          def self?.values: -> ::Array[Dedalus::Models::Machines::PreviewCreateParams::visibility]
        end
      end
    end
  end
end
