module Dedalus
  module Models
    module Machines
      type ssh_session_list =
        { items: ::Array[Dedalus::Machines::SSHSession]?, next_cursor: String }

      class SSHSessionList < Dedalus::Internal::Type::BaseModel
        attr_accessor items: ::Array[Dedalus::Machines::SSHSession]?

        attr_reader next_cursor: String?

        def next_cursor=: (String) -> String

        def initialize: (
          items: ::Array[Dedalus::Machines::SSHSession]?,
          ?next_cursor: String
        ) -> void

        def to_hash: -> {
          items: ::Array[Dedalus::Machines::SSHSession]?,
          next_cursor: String
        }
      end
    end
  end
end
