module Dedalus
  module Models
    module Machines
      type terminal_server_event =
        Dedalus::Machines::TerminalOutputEvent
        | Dedalus::Machines::TerminalErrorEvent
        | Dedalus::Machines::TerminalClosedEvent

      module TerminalServerEvent
        extend Dedalus::Internal::Type::Union

        def self?.variants: -> ::Array[Dedalus::Models::Machines::terminal_server_event]
      end
    end
  end
end
