module Dedalus
  module Models
    module Machines
      type terminal_error_event =
        {
          type: Dedalus::Models::Machines::TerminalErrorEvent::type_,
          error_code: String,
          error_message: String
        }

      class TerminalErrorEvent < Dedalus::Internal::Type::BaseModel
        attr_accessor type: Dedalus::Models::Machines::TerminalErrorEvent::type_

        attr_reader error_code: String?

        def error_code=: (String) -> String

        attr_reader error_message: String?

        def error_message=: (String) -> String

        def initialize: (
          type: Dedalus::Models::Machines::TerminalErrorEvent::type_,
          ?error_code: String,
          ?error_message: String
        ) -> void

        def to_hash: -> {
          type: Dedalus::Models::Machines::TerminalErrorEvent::type_,
          error_code: String,
          error_message: String
        }

        type type_ = :error

        module Type
          extend Dedalus::Internal::Type::Enum

          ERROR: :error

          def self?.values: -> ::Array[Dedalus::Models::Machines::TerminalErrorEvent::type_]
        end
      end
    end
  end
end
