module Dedalus
  module Models
    module Machines
      type terminal_create_params =
        {
          height: Integer,
          width: Integer,
          cwd: String,
          env: ::Hash[Symbol, String],
          shell: String
        }

      class TerminalCreateParams < Dedalus::Internal::Type::BaseModel
        attr_accessor height: Integer

        attr_accessor width: Integer

        attr_reader cwd: String?

        def cwd=: (String) -> String

        attr_reader env: ::Hash[Symbol, String]?

        def env=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        attr_reader shell: String?

        def shell=: (String) -> String

        def initialize: (
          height: Integer,
          width: Integer,
          ?cwd: String,
          ?env: ::Hash[Symbol, String],
          ?shell: String
        ) -> void

        def to_hash: -> {
          height: Integer,
          width: Integer,
          cwd: String,
          env: ::Hash[Symbol, String],
          shell: String
        }
      end
    end
  end
end
