module Dedalus
  module Models
    module Machines
      type terminal_list =
        { items: ::Array[Dedalus::Machines::Terminal]?, next_cursor: String }

      class TerminalList < Dedalus::Internal::Type::BaseModel
        attr_accessor items: ::Array[Dedalus::Machines::Terminal]?

        attr_reader next_cursor: String?

        def next_cursor=: (String) -> String

        def initialize: (
          items: ::Array[Dedalus::Machines::Terminal]?,
          ?next_cursor: String
        ) -> void

        def to_hash: -> {
          items: ::Array[Dedalus::Machines::Terminal]?,
          next_cursor: String
        }
      end
    end
  end
end
