module Dedalus
  module Models
    type machine_compute_usage_row =
      {
        awake_seconds: Integer,
        bucket_end: Time,
        bucket_start: Time,
        cpu_millicore_seconds: Integer,
        last_window_end: Time,
        machine_id: String,
        memory_mib_seconds: Integer,
        org_metering_bucket_ids: ::Array[String]?,
        requested_memory_mib: Integer,
        requested_storage_gib: Integer,
        requested_vcpu: Float,
        spec_fingerprint: String,
        stripe_cpu_identifiers: ::Array[String]?,
        stripe_memory_identifiers: ::Array[String]?,
        window_count: Integer,
        latest_stripe_emitted_at: Time
      }

    class MachineComputeUsageRow < Dedalus::Internal::Type::BaseModel
      attr_accessor awake_seconds: Integer

      attr_accessor bucket_end: Time

      attr_accessor bucket_start: Time

      attr_accessor cpu_millicore_seconds: Integer

      attr_accessor last_window_end: Time

      attr_accessor machine_id: String

      attr_accessor memory_mib_seconds: Integer

      attr_accessor org_metering_bucket_ids: ::Array[String]?

      attr_accessor requested_memory_mib: Integer

      attr_accessor requested_storage_gib: Integer

      attr_accessor requested_vcpu: Float

      attr_accessor spec_fingerprint: String

      attr_accessor stripe_cpu_identifiers: ::Array[String]?

      attr_accessor stripe_memory_identifiers: ::Array[String]?

      attr_accessor window_count: Integer

      attr_reader latest_stripe_emitted_at: Time?

      def latest_stripe_emitted_at=: (Time) -> Time

      def initialize: (
        awake_seconds: Integer,
        bucket_end: Time,
        bucket_start: Time,
        cpu_millicore_seconds: Integer,
        last_window_end: Time,
        machine_id: String,
        memory_mib_seconds: Integer,
        org_metering_bucket_ids: ::Array[String]?,
        requested_memory_mib: Integer,
        requested_storage_gib: Integer,
        requested_vcpu: Float,
        spec_fingerprint: String,
        stripe_cpu_identifiers: ::Array[String]?,
        stripe_memory_identifiers: ::Array[String]?,
        window_count: Integer,
        ?latest_stripe_emitted_at: Time
      ) -> void

      def to_hash: -> {
        awake_seconds: Integer,
        bucket_end: Time,
        bucket_start: Time,
        cpu_millicore_seconds: Integer,
        last_window_end: Time,
        machine_id: String,
        memory_mib_seconds: Integer,
        org_metering_bucket_ids: ::Array[String]?,
        requested_memory_mib: Integer,
        requested_storage_gib: Integer,
        requested_vcpu: Float,
        spec_fingerprint: String,
        stripe_cpu_identifiers: ::Array[String]?,
        stripe_memory_identifiers: ::Array[String]?,
        window_count: Integer,
        latest_stripe_emitted_at: Time
      }
    end
  end
end
