module Dedalus
  module Models
    type machine_compute_usage =
      {
        granularity: String,
        period_end: Time,
        period_start: Time,
        rows: ::Array[Dedalus::MachineComputeUsageRow]?
      }

    class MachineComputeUsage < Dedalus::Internal::Type::BaseModel
      attr_accessor granularity: String

      attr_accessor period_end: Time

      attr_accessor period_start: Time

      attr_accessor rows: ::Array[Dedalus::MachineComputeUsageRow]?

      def initialize: (
        granularity: String,
        period_end: Time,
        period_start: Time,
        rows: ::Array[Dedalus::MachineComputeUsageRow]?
      ) -> void

      def to_hash: -> {
        granularity: String,
        period_end: Time,
        period_start: Time,
        rows: ::Array[Dedalus::MachineComputeUsageRow]?
      }
    end
  end
end
