module Dedalus
  module Models
    type machine =
      {
        autosleep_seconds: Integer,
        desired_state: Dedalus::Models::Machine::desired_state,
        machine_id: String,
        memory_mib: Integer,
        phase: Dedalus::Models::Machine::phase,
        storage_gib: Integer,
        vcpu: Float
      }

    class Machine < Dedalus::Internal::Type::BaseModel
      attr_accessor autosleep_seconds: Integer

      attr_accessor desired_state: Dedalus::Models::Machine::desired_state

      attr_accessor machine_id: String

      attr_accessor memory_mib: Integer

      attr_accessor phase: Dedalus::Models::Machine::phase

      attr_accessor storage_gib: Integer

      attr_accessor vcpu: Float

      def initialize: (
        autosleep_seconds: Integer,
        desired_state: Dedalus::Models::Machine::desired_state,
        machine_id: String,
        memory_mib: Integer,
        phase: Dedalus::Models::Machine::phase,
        storage_gib: Integer,
        vcpu: Float
      ) -> void

      def to_hash: -> {
        autosleep_seconds: Integer,
        desired_state: Dedalus::Models::Machine::desired_state,
        machine_id: String,
        memory_mib: Integer,
        phase: Dedalus::Models::Machine::phase,
        storage_gib: Integer,
        vcpu: Float
      }

      type desired_state = :running | :sleeping | :destroyed

      module DesiredState
        extend Dedalus::Internal::Type::Enum

        RUNNING: :running
        SLEEPING: :sleeping
        DESTROYED: :destroyed

        def self?.values: -> ::Array[Dedalus::Models::Machine::desired_state]
      end

      type phase =
        :accepted
        | :placement_pending
        | :starting
        | :running
        | :stopping
        | :sleeping
        | :destroying
        | :destroyed
        | :failed

      module Phase
        extend Dedalus::Internal::Type::Enum

        ACCEPTED: :accepted
        PLACEMENT_PENDING: :placement_pending
        STARTING: :starting
        RUNNING: :running
        STOPPING: :stopping
        SLEEPING: :sleeping
        DESTROYING: :destroying
        DESTROYED: :destroyed
        FAILED: :failed

        def self?.values: -> ::Array[Dedalus::Models::Machine::phase]
      end
    end
  end
end
