module Dedalus
  module Models
    type machine_update_params =
      { machine_id: String } & Dedalus::Internal::Type::request_parameters

    class MachineUpdateParams < Dedalus::Models::UpdateParams
      extend Dedalus::Internal::Type::RequestParameters::Converter
      include Dedalus::Internal::Type::RequestParameters

      def machine_id: -> String

      def machine_id=: (String _) -> String

      def initialize: (
        machine_id: String,
        ?request_options: Dedalus::request_opts
      ) -> void

      def to_hash: -> {
        machine_id: String,
        request_options: Dedalus::RequestOptions
      }
    end
  end
end
