module Dedalus
  module Models
    type machine_storage_usage =
      {
        period_end: Time,
        period_start: Time,
        rows: ::Array[Dedalus::MachineStorageUsageRow]?
      }

    class MachineStorageUsage < Dedalus::Internal::Type::BaseModel
      attr_accessor period_end: Time

      attr_accessor period_start: Time

      attr_accessor rows: ::Array[Dedalus::MachineStorageUsageRow]?

      def initialize: (
        period_end: Time,
        period_start: Time,
        rows: ::Array[Dedalus::MachineStorageUsageRow]?
      ) -> void

      def to_hash: -> {
        period_end: Time,
        period_start: Time,
        rows: ::Array[Dedalus::MachineStorageUsageRow]?
      }
    end
  end
end
