module Dedalus
  module Models
    type org_usage =
      {
        billed_awake_seconds: Integer,
        billed_cpu_millicore_seconds: Integer,
        billed_logical_storage_mib_seconds: Integer,
        billed_memory_mib_seconds: Integer,
        included_storage_gib: Integer,
        plan_slug: String,
        provisioned_storage_gib: Integer
      }

    class OrgUsage < Dedalus::Internal::Type::BaseModel
      attr_accessor billed_awake_seconds: Integer

      attr_accessor billed_cpu_millicore_seconds: Integer

      attr_accessor billed_logical_storage_mib_seconds: Integer

      attr_accessor billed_memory_mib_seconds: Integer

      attr_accessor included_storage_gib: Integer

      attr_accessor plan_slug: String

      attr_accessor provisioned_storage_gib: Integer

      def initialize: (
        billed_awake_seconds: Integer,
        billed_cpu_millicore_seconds: Integer,
        billed_logical_storage_mib_seconds: Integer,
        billed_memory_mib_seconds: Integer,
        included_storage_gib: Integer,
        plan_slug: String,
        provisioned_storage_gib: Integer
      ) -> void

      def to_hash: -> {
        billed_awake_seconds: Integer,
        billed_cpu_millicore_seconds: Integer,
        billed_logical_storage_mib_seconds: Integer,
        billed_memory_mib_seconds: Integer,
        included_storage_gib: Integer,
        plan_slug: String,
        provisioned_storage_gib: Integer
      }
    end
  end
end
