module Dedalus
  module Models
    type usage_machine_storage_params =
      { machine_id: String, period_end: String, period_start: String }
      & Dedalus::Internal::Type::request_parameters

    class UsageMachineStorageParams < Dedalus::Internal::Type::BaseModel
      extend Dedalus::Internal::Type::RequestParameters::Converter
      include Dedalus::Internal::Type::RequestParameters

      attr_reader machine_id: String?

      def machine_id=: (String) -> String

      attr_reader period_end: String?

      def period_end=: (String) -> String

      attr_reader period_start: String?

      def period_start=: (String) -> String

      def initialize: (
        ?machine_id: String,
        ?period_end: String,
        ?period_start: String,
        ?request_options: Dedalus::request_opts
      ) -> void

      def to_hash: -> {
        machine_id: String,
        period_end: String,
        period_start: String,
        request_options: Dedalus::RequestOptions
      }
    end
  end
end
