module Dedalus
  module Resources
    class Usage
      def retrieve: (
        ?period_start: String,
        ?request_options: Dedalus::request_opts
      ) -> Dedalus::OrgUsage

      def machine_compute: (
        ?granularity: String,
        ?machine_id: String,
        ?period_end: String,
        ?period_start: String,
        ?request_options: Dedalus::request_opts
      ) -> Dedalus::MachineComputeUsage

      def machine_storage: (
        ?machine_id: String,
        ?period_end: String,
        ?period_start: String,
        ?request_options: Dedalus::request_opts
      ) -> Dedalus::MachineStorageUsage

      def initialize: (client: Dedalus::Client) -> void
    end
  end
end
